key: 
secret: 
auth_url: https://oauth.oclc.org/auth
token_url: https://oauth.oclc.org/token
metadata_service_url: https://worldcat.org
searchv2_url: https://americas.discovery.api.oclc.org/worldcat/search/v2

